company/urls.py
from django.urls import path

from .views import (

    CompanyListView,
    CompanyCreateView,
    CompanyDetailView,
    CompanyUpdateView,

    Company_list_view,
    Company_create_view,
    Company_detail_view,
    Company_update_view,

    icon_library,

)

app_name = "company"

urlpatterns = [

    # generic class based views
    path('', CompanyListView.as_view(), name='company-list'),
    path('create/', CompanyCreateView.as_view(), name='company-create'),
    path('<str:slug>/', CompanyDetailView.as_view(), name='company-detail'),
    path('<str:slug>/update/', CompanyUpdateView.as_view(), name='company-update'),

    # function based views
    path('function/based-views/', Company_list_view, name='company-function-list'),
    path('function/based-views/create/', Company_create_view, name='company-function-create'),
    path('function/based-views/<str:slug>/', Company_detail_view, name='company-function-detail'),
    path('function/based-views/<str:slug>/update/', Company_update_view, name='company-function-update'),

    path('icon-library/icons/', icon_library, name='icon-library'),

]

djangoProject4/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path("", include("company.urls", namespace="company")),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.translation import pgettext_lazy
from django_countries.fields import Country, CountryField
from django.db.models import Q, Value
from django.utils import timezone
from django.utils.translation import gettext as _
from company.utilities import SlugableModel


class AddressQueryset(models.QuerySet):
    def annotate_default(self, user):
        # Set default shipping/billing address pk to None
        # if default shipping/billing address doesn't exist
        default_shipping_address_pk, default_billing_address_pk = None, None
        if user.default_shipping_address:
            default_shipping_address_pk = user.default_shipping_address.pk
        if user.default_billing_address:
            default_billing_address_pk = user.default_billing_address.pk

        return user.addresses.annotate(
            user_default_shipping_address_pk=Value(
                default_shipping_address_pk, models.IntegerField()
            ),
            user_default_billing_address_pk=Value(
                default_billing_address_pk, models.IntegerField()
            ),
        )


class Address(SlugableModel):
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    company_name = models.CharField(max_length=256, blank=True)
    street_address_1 = models.CharField(max_length=256, blank=True)
    street_address_2 = models.CharField(max_length=256, blank=True)
    city = models.CharField(max_length=256, blank=True)
    city_area = models.CharField(max_length=128, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    country = CountryField()
    country_area = models.CharField(max_length=128, blank=True)
    phone = models.CharField(max_length=10, blank=True, default="")

    objects = AddressQueryset.as_manager()

    class Meta:
        ordering = ("pk",)

    @property
    def full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __str__(self):
        if self.company_name:
            return "%s - %s" % (self.company_name, self.full_name)
        return self.full_name

    def __eq__(self, other):
        if not isinstance(other, Address):
            return False
        return self.as_data() == other.as_data()

    __hash__ = models.Model.__hash__


    def get_copy(self):
        """Return a new instance of the same address."""
        return Address.objects.create(**self.as_data())

class UserManager(BaseUserManager):
    def create_user(
        self, email, password=None, is_staff=False, is_active=True, **extra_fields
    ):
        """Create a user instance with the given email and password."""
        email = UserManager.normalize_email(email)
        # Google OAuth2 backend send unnecessary username field
        extra_fields.pop("username", None)

        user = self.model(
            email=email, is_active=is_active, is_staff=is_staff, **extra_fields
        )
        if password:
            user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        return self.create_user(
            email, password, is_staff=True, is_superuser=True, **extra_fields
        )

    def customers(self):
        return self.get_queryset().filter(
            Q(is_staff=False) | (Q(is_staff=True) & Q(orders__isnull=False))
        )

    def staff(self):
        return self.get_queryset().filter(is_staff=True)



class User(PermissionsMixin, AbstractBaseUser, SlugableModel):
    """
    1 - admin will only be the owner of the SAAS
    2 - shop owner is the user linked to the company that pays for the saas
    3 - shop employee will be the user employed by the client company ( shop owner )
    4 - client will be the people consuming the end service
    """

    USER_TYPE = (
        ("admin", _("admin")),
        ("owner", _("owner")),
        ("employee", _("employee")),
        ("client", _("client")),
        ("unset", _("unset"))
    )
    user_type = models.CharField(choices=USER_TYPE, default="owner", max_length=100)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_online = models.BooleanField(default=False)
    note = models.TextField(null=True, blank=True)
    date_joined = models.DateTimeField(default=timezone.now, editable=False)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, blank=True, null=True)
    avatar = models.ImageField(upload_to='avatar', blank=False)

    USERNAME_FIELD = "email"

    objects = UserManager()

    class Meta:
        permissions = (
            (
                "manage_users",
                pgettext_lazy("Permission description", "Manage customers."),
            ),
            ("manage_staff", pgettext_lazy("Permission description", "Manage staff.")),
            (
                "impersonate_users",
                pgettext_lazy("Permission description", "Impersonate customers."),
            ),
        )

    def __str__(self):
        return str(self.first_name) or ""

    def get_agnostic_included_fields(self):
        return ["email", "first_name", "last_name", "avatar"]

    def get_agnostic_special_fields(self):
        return []

    def get_full_name(self):
        if self.first_name or self.last_name:
            return ("%s %s" % (self.first_name, self.last_name)).strip()
        if self.address:
            first_name = self.address.first_name
            last_name = self.address.last_name
            if first_name or last_name:
                return ("%s %s" % (first_name, last_name)).strip()
        return self.email

    def get_absolute_edit_url(self):
        if self.is_staff:
            return reverse("staff:staff-edit", kwargs={
                'slug': self.slug
            })
        else:
            return reverse("customer:customer-update", kwargs={
                'slug': self.slug
            })

    def get_short_name(self):
        return self.email

    def get_ajax_label(self):
        address = self.default_billing_address
        if address:
            return "%s %s (%s)" % (address.first_name, address.last_name, self.email)
        return self.email

class Company(SlugableModel):

    class Meta:
        verbose_name = _("Company")
        verbose_name_plural = _("companies")

    # this is the company which is the client attached to the account
    # do not overwrite the save method as it lives in the SlugableModel

    rpps = models.CharField(max_length=11, blank=True)
    adeli = models.CharField(max_length=11, blank=True)
    name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    date_of_birth = models.DateTimeField(null=True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, blank=True, null=True)
    mobile = models.CharField(max_length=10, blank=True, default="")
    telephone = models.CharField(max_length=10, blank=True, default="")
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}" or ""

    def get_absolute_url(self):
        return reverse(
                    "company:company-detail",
                    kwargs={"slug": self.slug}
                   )

    def get_full_name(self):
        if self.first_name or self.last_name:
            return ("%s %s" % (self.first_name, self.last_name)).strip()
        if self.address:
            first_name = self.address.first_name
            last_name = self.address.last_name
            if first_name or last_name:
                return ("%s %s" % (first_name, last_name)).strip()
        return self.email

class StoreImages(SlugableModel):


    class Meta:
        verbose_name = "Store Image"
        verbose_name_plural = "Store Images"

    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name="pictures")
    logo = models.ImageField(upload_to='shop/logo', blank=True)
    front = models.ImageField(upload_to='shop/front', blank=True)
    inside = models.ImageField(upload_to='shop/inside', blank=True)


    def __str__(self):
        return f"{self.company}" or ""

company/forms.py
from django import forms

from company.models import Company
from company.utilities import CommonFormHelper


class CompanyUpdateForm(forms.ModelForm):
    """
    The models forms are like the generic class based views which enables us
    to get the work done directly from the model
    We specify the models and their fields
    we can exclude fields as well
    """

    class Meta:
        model = Company
        fields = ["rpps", "adeli", "email", "first_name",
                  "last_name", "date_of_birth"]
        exclude = ["slug"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["date_of_birth"] = forms.DateField(required=False,
                                                       widget=forms.DateInput(
                                                            attrs={'type': "date",
                                                                   'data-date-container': "#datepicker1",
                                                                   'data-provide': "datepicker",
                                                                   'class': "form-control ",
                                                                   'id': 'datepicker1'
                                                                   }
                                                       ))

company/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.utils.translation import gettext as _
from company.forms import CompanyUpdateForm
from company.models import Company

"""
The 4 views down below are generic django class based views
imported above from django.views.generic
"""

class CompanyListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Company
    template_name = "company/company_list.html"
    permission_required = ["eshop.manage_companies"]

    def get_context_data(self, **kwargs):
        context = super(CompanyListView, self).get_context_data()
        """ 
        the basic object will be object_list
        With generic class based view on the listview and the detailview
        you can supercharge the context to make object available in templates
        'as seen bellow if I use {{available_variable_in_template }} in the templates 
        it will render Hello world 
        """
        context["available_variable_in_template"] = "Hello world"
        return context



class CompanyDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Company
    template_name = "company/company_detail.html"
    permission_required = ["eshop.manage_companies"]

    def get_queryset(self):
        context = super(CompanyDetailView, self).get_queryset()
        print(context.prefetch_related('pictures').query)
        return context.prefetch_related('pictures')

    def get_context_data(self, **kwargs):
        context = super(CompanyDetailView, self).get_context_data()

        """
        as seen above you can pass extra variables to overcha   rge the context
        """
        return context


"""
In the two examples below weither we specify fields
or we can use form_class

"""
class CompanyCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Company
    permission_required = ["eshop.manage_companies"]
    fields = ["rpps", "adeli", "email", "first_name", "last_name", "date_of_birth"]
    template_name = "company/company_create.html"


class CompanyUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Company
    permission_required = ["eshop.manage_companies"]
    form_class = CompanyUpdateForm
    template_name = "company/company_update.html"



def Company_list_view(request, *args, **kwargs):
    context = {}
    context["object_list"] = Company.objects.all()
    return render(request, "company/company_list.html", context)

def Company_create_view(request, *args, **kwargs):
    context = {}
    form = CompanyUpdateForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, _("The form was updated"))
        object = Company.objects.get(slug=kwargs["slug"])
        return redirect(reverse_lazy("company:company-detail", kwargs={"slug": object.slug}))
    context["form"] = CompanyUpdateForm(instance=object)
    return render(request, "company/company_create.html", context)


def Company_detail_view(request, *args, **kwargs):
    context = {}
    context["object"] = Company.objects.get(slug=kwargs["slug"])
    return render(request, "company/company_detail.html", context)


def Company_update_view(request, *args, **kwargs):
    context = {}
    object = Company.objects.get(slug=kwargs["slug"])
    form = CompanyUpdateForm(request.POST or None, instance=object)
    if form.is_valid():
        form.save()
        messages.success(request, _("The form was updated"))
        return redirect(reverse_lazy("company:company-detail", kwargs={"slug": object.slug}))
    context["form"] = CompanyUpdateForm(instance=object)
    return render(request, "company/company_update.html", context)


def icon_library(request, *args, **kwargs):
    context = {}
    return render(request, "admin/icon_library.html", context)

company/templates/company/company_create.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="card">
        <div class="card-body">
            <h4 class="fw-bold mb-3">{% trans "Create company" %}</h4>
            <form method="post" action="" novalidate class="needs-validation">
            <div class="row">
                {% crispy form %}
                <button class="btn btn-outline-primary " type="submit">{% trans "Submit" %}</button>
            </div>
            </form>
        </div>
    </div>

{% endblock %}


{% block extra_javascript %}
<script>
    $(".form-group").addClass("col-6 mb-3");
</script>
{% endblock %}

company/templates/company/company_detail.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block contents %}
<div class="row">
  <div class="col-md-4 order-md-0 order-sm-1 order-1">
    <div class="card overflow-hidden">
      <div class="bg-primary bg-soft">
        <div class="row">
          <div class="col-7">
            <div class="text-primary p-3 mb-2">
              <p class="text-dark m-0">{{ object.type_client }}</p>
              <h4 class="text-primary font-weight-bolder">
                {{ object.prenom|capfirst }} {{ object.nom|capfirst }}</h4>
            </div>
          </div>
          <div class="col-5 align-self-end">
              <img src="" alt="" class="img-fluid" style="height: 72px;"
                 kasperskylab_antibanner="on">
              {% if object.is_online %}
                    <i class="mdi mdi-record text-success"></i>
                    <span class="text-lowercase text-muted">
                        {% trans "Online" %}
                    </span>
                {% else %}
                    <i class="mdi mdi-record text-danger"></i>
                    <span class="text-lowercase text-muted">
                        {% trans "Offline" %}
                    </span>
                {% endif %}
          </div>
        </div>
      </div>
      <div class="card-body pt-0">
        <div class="row">
          <div class="col-sm-4">
            <div class="avatar-md profile-user-wid mb-4">
              <img src="{% if object.pictures.logo %}{{ object.pictures.logo.url }}{% else %}{% static 'images/default-shop.png' %}{% endif %}" alt=""
                   class="img-thumbnail rounded" style="height: 100%" kasperskylab_antibanner="on">
            </div>
            <h5 class="font-size-15 text-truncate">
                {% if object.get_full_name != object.email %}
                      {{ object.get_full_name }}
                {% else %}
                  -
                {% endif %}
            </h5>
            <p class="font-size-11 text-muted mb-0">
                {% if object.date_joined %}
                    {% trans "joined" context "Company field" %}
                    {{ object.date_joined }}
                {% endif %}
            </p>
          </div>

          <div class="col-sm-8">
            <div class="pt-4">

              <div class="mt-0 ">
              <a href="{% url "company:company-update" slug=object.slug %}" class="btn btn-outline-primary btn-sm float-end mb-2">
                {% trans "Edit company" context "company action" %}<i class="mdi mdi-arrow-right ms-2"></i>
              </a>

              {% if perms.account.impersonate_users %}
                <a href="{% url 'company:company-list' %}" class="btn btn-outline-primary btn-sm float-end mb-2 waves-effect">
                  {% trans 'Back to list' context 'Company back to list' %}<i class="mdi mdi-arrow-right ms-2"></i>
                </a>
              {% endif %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end card -->
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">
                    {% trans "Some card with informations" %}
                </h4>
            </div>
        </div>

  </div>
  <div class="col-md-8 order-md-1 order-sm-0 order-0">
    <ul class="nav nav-tabs nav-fill mb-3" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-bs-toggle="tab" href="#orders" role="tablist" aria-controls="orders"
           aria-selected="true">  {% trans "Recent orders" context "Company recent orders table title" %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" href="#notes" role="tablist" aria-controls="notes"
           aria-selected="false"> {% trans "Company notes" context "Company notes card title" %}</a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade active show" id="orders" role="tabpanel">
        <div class="card">
        <div class="card-body">
        <div class="data-table-header">
          <h5 class="data-table-title">
            {% trans "Recent orders" context "Customer recent orders table title" %}
          </h5>
        </div>
          <div class="table-responsive">
                <table class="table align-middle table-nowrap table-hover myTable">
              <thead>
                <tr>
                   <td>{% trans "pk" context "Orders table header" %}</td>

                  <td>{% trans "Placed on" context "Orders table header" %}</td>

                  <td>{% trans "Payment" context "Orders table header" %}</td>

                  <td>{% trans "Order" context "Orders table header" %}</td>

                  <td>{% trans "Total" context "Orders table header" %}</td>
                    <td class="text-end fw-bold">
                        {% trans "Actions" %}
                    </td>
                </tr>
              </thead>
              <tbody>
              </tbody>
                </table>
          </div>

            </div>
        </div>
      </div>
      <div class="tab-pane fade" id="notes" role="tabpanel">
        <div class="card">
        <div class="card-body">
        <a class="base-form btn btn-light btn-sm float-end waves-effect" data-bs-toggle="modal" data-bs-target="#BaseModal">
            <i class="mdi mdi-plus-circle-outline text-success me-2 "></i>{% trans "Add note" context "Customer notes card action" %}
          </a>
          <p class="card-title mb-4">
            {% trans "Company notes" context "Customer notes card title" %}
          </p>

        </div>

      </div>
      </div>
    </div>


  </div>
</div>

    <div class="modal fade" id="BaseModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"  role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
            <form method="POST" action="" id="form-url" enctype="multipart/form-data" class="needs-validation" novalidate>
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-center" id="staticBackdropLabel">
                            <img class="me-2" src="{% static 'images/modal-logo.png' %}" alt="" height="22">
                                <span id="modal-title"></span></h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                            <div class="modal-body mb-0" >
                                {% csrf_token %}
                                <span id="form-receiver">
                                </span>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-light btn-sm" data-bs-dismiss="modal">
                                    {% trans "Cancel" %}
                                </button>
                                <button class="btn btn-primary btn-sm fk-adder-submit" type="submit">
                                    {% trans "Create" %}
                                </button>
                            </div></div>
                        </form>

            </div>
        </div>
{% endblock %}

company/templates/company/company_list.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block contents %}
<div class="card">
    <div class="card-body">


     <div class="table-responsive">
        <table class="table align-middle table-nowrap table-hover myTable">

        <thead>
            <tr>
                {% trans "Name" context "Orders table header" %}
                <th>
                {% trans "updated at" context "Orders table header" %}
                </th>
                <th>
                    {% trans "price" context "Orders table header" %}
                </th>
                <th class="text-end">{% trans "Action" %}</th>
            </tr>
        </thead>
    <tbody>
        {% for each in object_list %}
            <tr class="main-table">
                <td>
                <div class="media">
                    <img {% if each.images.first.image %}  src="{{ each.images.first.image.url }}" class="rounded avatar-xs"
                             {% else %}class="rounded avatar-xs border default-product"{% endif %} alt="{{ each.images.first.alt }}">
                        <div class="ms-2">
                             <a href="{{ each.get_absolute_url }}">
                                <p class="font-size-12 fw-bold text-uppercase text-muted mb-0">{{each|capfirst|truncatechars:15}}</p>
                                <small class="font-size-11 fw-semibold text-muted mb-0">
                                     {{ each.product_type|capfirst }}
                            </small>
                            </a>
                        </div>
                    </div>
                <td>
                    <span class="badge py-2 px-2 bg-info">
                        {{ each.updated_at|date:"d M Y" }}
                    </span>
                </td>
                <td></td>
                <td>
                    <div class="d-flex flex-row float-end">

                        <a class="text-info" href="{% url "company:company-detail" slug=each.slug %}"
                           data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans "View product details" %}">
                            <i class="mdi mdi-eye-outline font-size-18 me-2"></i></a>
                        <a class="text-success" href="{% url "company:company-update" slug=each.slug %}"
                           data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans "Edit product" %}">
                                <i class="mdi mdi-pencil-outline font-size-18 me-2"></i></a>




                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
        </table>
     </div>

    </div>
</div>

{% endblock %}

company/templates/company/company_update.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="card">
        <div class="card-body">
            <h4 class="fw-bold mb-3">{% trans "Edit company" %} : {{ object|capfirst }}</h4>
            <form method="post" action="" novalidate class="needs-validation">
            <div class="row">
                {% crispy form %}
                <button class="btn btn-outline-primary float-end" type="submit">{% trans "Update" %}</button>
            </div>
            </form>
        </div>
    </div>

{% endblock %}


{% block extra_javascript %}
<script>
    $(".form-group").addClass("col-6 mb-3");
</script>
{% endblock %}