company/urls.py
from django.urls import path

from .views import (

    CompanyListView,
    CompanyCreateView,
    CompanyDetailView,
    CompanyUpdateView,

    Company_list_view,
    Company_create_view,
    Company_detail_view,
    Company_update_view,

    icon_library,

)

app_name = "company"

urlpatterns = [

    # generic class based views
    path('', CompanyListView.as_view(), name='company-list'),
    path('create/', CompanyCreateView.as_view(), name='company-create'),
    path('<str:slug>/', CompanyDetailView.as_view(), name='company-detail'),
    path('<str:slug>/update/', CompanyUpdateView.as_view(), name='company-update'),

    # function based views
    path('function/based-views/', Company_list_view, name='company-function-list'),
    path('function/based-views/create/', Company_create_view, name='company-function-create'),
    path('function/based-views/<str:slug>/', Company_detail_view, name='company-function-detail'),
    path('function/based-views/<str:slug>/update/', Company_update_view, name='company-function-update'),

    path('icon-library/icons/', icon_library, name='icon-library'),

]

djangoProject4/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path("", include("company.urls", namespace="company")),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta content="la solution de gestion événementielle traiteur 360" name="description"/>
  <meta content="ordo" name="author"/>
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,700&display=swap" rel="stylesheet"
        type="text/css">

  <style>
        *{
            font-family:"Poppins", sans-serif;
        }

    </style>
  <style>

        input[switch="bool"]:checked + label {
            background-color: #f6ca55!important;
        }
        input[switch]:checked + label::before {
            font: normal normal normal 18px/1 "Material Design Icons"!important;
            padding-top: 2px!important;
            content: "\F0644"!important;
        }
        input[switch]:checked + label::after {
            font: normal normal normal 18px/1 "Material Design Icons"!important;
            padding-top: 2px!important;
            content: "\F035C"!important;
        }
        input[switch="bool"] + label {
            background-color: #f6ca55!important;
        }
        input[switch] + label::before {
            font: normal normal normal 18px/1 "Material Design Icons"!important;
            padding-top: 2px!important;
            content: "\F035C"!important;
        }
        input[switch] + label::after {
            font: normal normal normal 18px/1 "Material Design Icons"!important;
            padding-top: 2px!important;
            content: "\F0644"!important;
        }
        .olwski-yellow {
            color: #f6ca55;
        }
        .font-blue {
            color: #004777;
        }
        .animate-bottom {
          position: relative;
          animation: animatebottom 0.4s;
        }
        .modal-backdrop {
            opacity:0.3 !important;
            background-color: #gggg3;
        }
        @keyframes animatebottom {
          from {
            bottom: -100px;
            opacity: 0;
          }

          to {
            bottom: 0;
            opacity: 1;
          }
        }
        .nav-pills .nav-link.active,.nav-pills .show>.nav-link{color:#fff;background-color:#004777}
        .nav-pills .nav-link,.nav-pills>.nav-link{-webkit-box-flex:1;-ms-flex:1 1 auto;flex:1 1 auto;border: 1px solid #d1dee7!important;text-align:center}
    </style>
  <title>{% block title %} Ordo | {{ object }} {{ heading }}{% endblock %}</title>

  <!-- App favicon -->
  <link rel="shortcut icon" href="{% static 'images/ordo.png' %}">

  {% block extra_css %}
  {% endblock %}
{% block css%}
{% include 'css.html' %}
{% endblock %}


</head>


<body data-sidebar="light">


{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock %}

<div class="main-content">
  <div class="page-content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-12">
      <div style="top: 0px; right: 12px;width: 300px;position:absolute;word-wrap: break-word! important;z-index:5000;">
        {% if messages %}
        {% for message in messages %}
        <div class="toast fade show mb-1"  role="alert" data-bs-autohide="false" aria-atomic="true">
          <div class="toast-header bg-white">
            <img src="{% static 'images/ordo.png' %}" alt="" class="me-2" height="18">
            <strong class="me-auto">Ordo</strong>
            <small class="text-muted">get_nat_time</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body bg-white">
            <div class="d-flex flex-row">
                <span class="my-auto">
            {% if message.tags == 'alert-success' %}
            <i class="bx bx-check-circle h4 text-success me-3"></i>
            {% elif message.tags == 'alert-warning' %}
            <i class="bx bx-error h4 text-warning me-3"></i>
            {% elif message.tags == 'alert-danger' %}
            <i class="font-size-20 bx bx-no-entry h4 text-danger me-3"></i>
            {% else %}
            <i class="mdi mdi-alert-circle-outline h4 text-info me-3"></i>
            {% endif %}</span>
              <span>{{ message }}</span>

            </div>
          </div>
        </div>

      {% endfor %}
        {% endif %}
      </div></div>
      </div>

      {% block contents %}
      {% endblock %}

  </div>


{% block r_sidebar %}
{% endblock %}


{% block javascript %}
{% include 'javascript.html'%}
{% endblock %}
{% block extra_javascript %}
{% endblock %}
  </div>

</div>

</body>

</html>

templates/css.html
{% load static %}
{% block css%}

<link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css"/>

<!-- Bootstrap Css -->
<link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css"/>

<link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css"/>

<link href="{% static 'libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet"
      type="text/css"/>
<link href="{% static 'libs/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'libs/spectrum-colorpicker2/spectrum.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'libs/bootstrap-timepicker/css/bootstrap-timepicker.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet"
      type="text/css"/>
<link rel="stylesheet" href="{% static 'libs/@chenfengyuan/datepicker/datepicker.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'libs/toastr/build/toastr.min.css' %}">
<link href="{% static 'libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'libs/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/6.5.95/css/materialdesignicons.min.css" rel="stylesheet">
<link href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css" rel="stylesheet">
<link href="{% static 'css/datepicker.min.css' %}" >

{% endblock%}

templates/footer.html
{% load static %}
{% load i18n %}
<footer class="text-white" style="background-color: #004777;padding: 0">
  <div class="container">

    <!-- end row -->
            <hr class="footer-border my-2">

            <div class="d-flex flex-row justify-content-around">


        <p class="font-size-12 mb-2 pb-3">©
          <script>document.write(new Date().getFullYear())</script>
          All Right Reserved. {% trans 'Made with' %} <i class="mdi mdi-heart text-danger"></i> {% trans 'by' %}
          <a href="https://nsft.fr">N.S.F.T</a></p>
          <p>Mentions Légales R.G.P.D
                CGU - CGV</p>
      </div>


    </div>
  </div>
  <!-- end container -->
</footer>

templates/header.html
{% load static %}
{% load humanize %}

{% block header %}
<header id="page-topbar">

    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/ordo-blue.png'%}" alt="" height="42">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/ordo-blue.png'%}" alt="" height="42">
                    </span>
                </a>

                <a href="" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/ordo-mini-logo.png'%}" alt="" height="25">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/letter.png'%}" alt="" height="25">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect d-flex d-lg-none" id="vertical-menu-btn">
                <i class="mdi mdi-filter-outline my-auto font-size-20"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" id="myInput" placeholder="Rechercher...">
                    <span class="bx bx-search-alt"></span>
                </div>
            </form>


        </div>

        <div class="d-flex">

            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                     aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..."
                                       aria-label="Recipient's username">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i
                                            class="mdi mdi-magnify"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-customize"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                    <div class="px-lg-2">
                        <div class="row g-0">
                            <div class="col">
                                <a class="dropdown-icon-item" href="/site">
                                    <img src="{% static 'images/website-integre-traiteur.png'%}" alt="site">
                                    <span>Site</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="/blog">
                                    <img src="{% static 'images/blog.png'%}" alt="blog">
                                    <span>Blog</span>
                                </a>
                            </div>
                            <div class="col">
                                <a class="dropdown-icon-item" href="/social">
                                    <img src="{% static 'images/social-icons.png'%}" alt="réseaux">
                                    <span>Réseaux sociaux</span>
                                </a>
                            </div>
                        </div>

                        <div class="row g-0">
                            <div class="col">
                                <a class="dropdown-icon-item" href="#">
                                    <img src="{% static 'images/marketing.png'%}" alt="marketing">
                                    <span>Marketing</span>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>


            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                        id="page-header-notifications-dropdown" data-bs-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                    {% if notif.count != 0 %}
                    <i class="bx bx-bell bx-tada" id="turnoff-bell"></i>
                    <span class="badge bg-danger rounded-pill" data-value="{{notif.count}}" id="notif-counter">{{notif.count}}</span>
                    {% else %}
                     <i class="bx bx-bell"></i>
                    {% endif %}
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                     aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0" key="t-notifications"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="" class="small" key="t-view-all"> Tout Voir</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        {% for each in notif %}
                        <a class="text-reset notification-item notification-item-{{ each.slug }}">
                            <div class="media">
                                <div class="avatar-xs me-3">
                                          {% if each.sender %}
                                          <img class="avatar-xs rounded-circle me-3" src="{% if each.sender.avatar %}{{each.sender.avatar.url}}{% else %}{% static 'images/avatar.png' %}{% endif %}" alt="">
                                          {% else %}
                                            <span class="avatar-title bg-primary rounded-circle font-size-16">
                                                  <i class="bx bx-tada"></i>
                                                </span>
                                          {% endif %}

                                </div>
                                <div class="media-body">
                                    <h6 class="mt-0 mb-1" key="t-your-order">

                                        <span class="text-info"> {{each.titre|capfirst }}</span>
                                    </h6>
                                    <div class="text-muted">
                                        <p class="font-size-12 mb-1" key="t-grammer">{{ each.message }}</p>
                                        <p class="mb-0">
                                            <i class="mdi mdi-clock-outline"></i>
                                            <span key="t-min-ago">{{ each.date_creation|naturaltime }}</span></p>
                                    </div>
                                </div>
                                <div class="ms-auto">
                                    <input class="mark-as-seen" type="checkbox" id="{{ each.slug }}">
                                </div>
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                    <div class="p-2 border-top d-grid">
                        <a class="btn btn-sm btn-link font-size-14 text-center" href="">
                            <i class="mdi mdi-arrow-right-circle me-1"></i> <span key="t-view-more">Voir plus ...</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.avatar %}
                    <img src="{{ request.user.avatar.url }}" alt=""
                         class="rounded-circle header-profile-user">
                    {% else %}
                    <img src="{% static 'images/avatar.png' %}" alt=""
                         class="rounded-circle header-profile-user">
                    {% endif %}
                    <span class="d-none d-xl-inline-block ms-1" key="t-henry">{{user.username|capfirst}}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">

                    <a class="dropdown-item" href="#"><i class="bx bx-lock-open font-size-16 align-middle me-1"></i>
                        <span key="t-lock-screen">Véroullié</span></a>
                    <div class="dropdown-divider"></div>
                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href=""><i
                            class="bx bx-key font-size-16 align-middle me-1"></i> Modifier Mot de passe</a>
                    <a class="dropdown-item text-danger" href=""><i
                            class="bx bx-log-out font-size-16 align-middle me-1 text-danger"></i> Se deconnecter</a>
                    {% else %}
                    <a class="dropdown-item " href=""><i
                            class="bx bx-log-in font-size-16 align-middle me-1 "></i> Se connecter</a>
                    {% endif %}
                </div>
            </div>
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item font-size-16">
                    <i class="mdi mdi-heart-outline font-size-20"></i>
                </button>
            </div>
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item right-bar-toggle font-size-16">
                    <i class="mdi mdi-cart-outline font-size-20"></i>
                </button>
            </div>

        </div>
    </div>
</header>
{% endblock %}

<!--{% block extra_javascript %}-->
<!--{{ room_name|json_script:"room-name" }}-->
<!--<script>-->
<!--        const roomName = JSON.parse(document.getElementById('room-name').textContent);-->

<!--        const notificationSocket = new WebSocket(-->
<!--            'ws://'-->
<!--            + window.location.host-->
<!--            + '/ws/notification/'-->
<!--            + roomName-->
<!--            + '/'-->
<!--        );-->

<!--        notificationSocket.onmessage = function(e) {-->
<!--            const data = JSON.parse(e.data);-->
<!--           // document.querySelector('#chat-log').value += (data.message + '\n');-->
<!--        };-->

<!--        notificationSocket.onclose = function(e) {-->
<!--            console.error('Chat socket closed unexpectedly');-->
<!--        };-->

<!--</script>-->
<!--{% endblock %}-->

templates/javascript.html
{% load static %}
{% block javascript %}
<!-- JAVASCRIPT -->
<script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'libs/jquery-ui-dist/jquery-ui.min.js' %}"></script>

<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap-tab.js' %}"></script>
<script src="{% static 'libs/metismenu/metisMenu.min.js' %}"></script>
<script src="{% static 'libs/select2/js/select2.min.js' %}"></script>
<script src="{% static 'libs/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>
<script src="{% static 'libs/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}"></script>
<script src="{% static 'libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>

<script src="{% static 'libs/table-edits/build/table-edits.min.js' %}"></script>
<!-- Sweet Alerts js -->
<script src="{% static 'libs/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Sweet alert init js-->
<script src="{% static 'js/pages/sweet-alerts.init.js' %}"></script>
{#<script src="{% static 'js/pages/table-editable.int.js' %}"></script>#}
<!-- jquery step -->

<script src="{% static 'libs/toastr/build/toastr.min.js' %}"></script>
<script src="{% static 'libs/tui-chart/tui-chart-all.min.js' %}"></script>

<!-- toastr init -->
<script src="{% static 'js/pages/toastr.init.js' %}"></script>
<!-- form advanced init -->
<script src="{% static 'js/pages/form-advanced.init.js' %}"></script>
<!-- Session timeout js -->
<script src="{% static 'js/pages/validation.init.js' %}"></script>

<script src="{% static 'js/app.js' %}"></script>

<script>

$('.container-fluid').show();

</script>
<script defer>
$.ajax({
   url: '/clients/defered-cart',
   method: 'GET',
   dataType: 'json',
   success: function(response) {
       $('#cart-sidebar').html(response.frame);
   }
});

</script>
{% endblock %}

templates/sidebar.html
{% load static %}
{% load i18n %}

{% block sidebar %}
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">
    <div data-simplebar class="h-100">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title" key="t-menu">{% trans "Dashboard" context "Dashboard dashboard" %}</li>
                    <li>
                        <a href="/" class="waves-effect">
                            <i class="mdi mdi-monitor-dashboard"></i>
                            <span key="t-dashboard">{% trans "Dashboard" context "Dashboard dashboard" %}</span>
                        </a>
                    </li>
                      <li>
                        <a href="{% url "company:company-list" %}" class="waves-effect">
                            <i class="mdi mdi-database-lock"></i>
                            <span class="badge rounded-pill bg-info float-end"></span>
                            <span key="t-bdd">{% trans "Company list" %}</span>
                        </a>
                    </li>
                     <li>
                        <a href="{% url "company:icon-library" %}" class="waves-effect">
                            <i class="mdi mdi-simple-icons"></i>
                            <span class="badge rounded-pill bg-info float-end"></span>
                            <span key="t-bdd">{% trans "Icon library" %}</span>
                        </a>
                    </li>


        </ul>
        </div>

        </div>
    </div>

{% endblock %}